// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../testutils/mocks/expense/repository_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/financeapp/backend/internal/domain"
	expense "github.com/financeapp/backend/internal/expense"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CategorySummary mocks base method.
func (m *MockRepository) CategorySummary(userID uuid.UUID, start, end time.Time) ([]*expense.CategorySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategorySummary", userID, start, end)
	ret0, _ := ret[0].([]*expense.CategorySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CategorySummary indicates an expected call of CategorySummary.
func (mr *MockRepositoryMockRecorder) CategorySummary(userID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategorySummary", reflect.TypeOf((*MockRepository)(nil).CategorySummary), userID, start, end)
}

// Create mocks base method.
func (m *MockRepository) Create(arg0 *domain.Expense) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), arg0)
}

// CreateBatch mocks base method.
func (m *MockRepository) CreateBatch(expenses []*domain.Expense) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", expenses)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockRepositoryMockRecorder) CreateBatch(expenses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockRepository)(nil).CreateBatch), expenses)
}

// Delete mocks base method.
func (m *MockRepository) Delete(id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), id, userID)
}

// DeleteByImportID mocks base method.
func (m *MockRepository) DeleteByImportID(importID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByImportID", importID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByImportID indicates an expected call of DeleteByImportID.
func (mr *MockRepositoryMockRecorder) DeleteByImportID(importID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByImportID", reflect.TypeOf((*MockRepository)(nil).DeleteByImportID), importID)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(id, userID uuid.UUID) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id, userID)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), id, userID)
}

// List mocks base method.
func (m *MockRepository) List(filter expense.ListFilter) ([]*domain.Expense, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", filter)
	ret0, _ := ret[0].([]*domain.Expense)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), filter)
}

// MonthlySummary mocks base method.
func (m *MockRepository) MonthlySummary(userID uuid.UUID, months int) ([]*expense.MonthlySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MonthlySummary", userID, months)
	ret0, _ := ret[0].([]*expense.MonthlySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MonthlySummary indicates an expected call of MonthlySummary.
func (mr *MockRepositoryMockRecorder) MonthlySummary(userID, months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MonthlySummary", reflect.TypeOf((*MockRepository)(nil).MonthlySummary), userID, months)
}

// Update mocks base method.
func (m *MockRepository) Update(arg0 *domain.Expense) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository)(nil).Update), arg0)
}
