// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../testutils/mocks/expense/service_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domain "github.com/financeapp/backend/internal/domain"
	expense "github.com/financeapp/backend/internal/expense"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(userID uuid.UUID, req *expense.CreateRequest) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, req)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), userID, req)
}

// Delete mocks base method.
func (m *MockService) Delete(id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), id, userID)
}

// GetByID mocks base method.
func (m *MockService) GetByID(id, userID uuid.UUID) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id, userID)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), id, userID)
}

// GetCategorySummary mocks base method.
func (m *MockService) GetCategorySummary(userID uuid.UUID, start, end time.Time) ([]*expense.CategorySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategorySummary", userID, start, end)
	ret0, _ := ret[0].([]*expense.CategorySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategorySummary indicates an expected call of GetCategorySummary.
func (mr *MockServiceMockRecorder) GetCategorySummary(userID, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategorySummary", reflect.TypeOf((*MockService)(nil).GetCategorySummary), userID, start, end)
}

// GetMonthlySummary mocks base method.
func (m *MockService) GetMonthlySummary(userID uuid.UUID, months int) ([]*expense.MonthlySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonthlySummary", userID, months)
	ret0, _ := ret[0].([]*expense.MonthlySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonthlySummary indicates an expected call of GetMonthlySummary.
func (mr *MockServiceMockRecorder) GetMonthlySummary(userID, months any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonthlySummary", reflect.TypeOf((*MockService)(nil).GetMonthlySummary), userID, months)
}

// List mocks base method.
func (m *MockService) List(userID uuid.UUID, req expense.ListRequest) (*expense.PaginatedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", userID, req)
	ret0, _ := ret[0].(*expense.PaginatedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), userID, req)
}

// Update mocks base method.
func (m *MockService) Update(id, userID uuid.UUID, req *expense.UpdateRequest) (*domain.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, userID, req)
	ret0, _ := ret[0].(*domain.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(id, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), id, userID, req)
}
