// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../testutils/mocks/importer/service_mock.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	multipart "mime/multipart"
	reflect "reflect"

	domain "github.com/financeapp/backend/internal/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Import mocks base method.
func (m *MockService) Import(userID uuid.UUID, file multipart.File, header *multipart.FileHeader) (*domain.Import, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", userID, file, header)
	ret0, _ := ret[0].(*domain.Import)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockServiceMockRecorder) Import(userID, file, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockService)(nil).Import), userID, file, header)
}

// ListImports mocks base method.
func (m *MockService) ListImports(userID uuid.UUID) ([]*domain.Import, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImports", userID)
	ret0, _ := ret[0].([]*domain.Import)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListImports indicates an expected call of ListImports.
func (mr *MockServiceMockRecorder) ListImports(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImports", reflect.TypeOf((*MockService)(nil).ListImports), userID)
}

// RevertImport mocks base method.
func (m *MockService) RevertImport(id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevertImport", id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevertImport indicates an expected call of RevertImport.
func (mr *MockServiceMockRecorder) RevertImport(id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertImport", reflect.TypeOf((*MockService)(nil).RevertImport), id, userID)
}
